<?php

namespace Application;

class Exception extends \Exception {

	const ASSERT	= 1;
	const WARNING 	= 2;
	const ERROR 	= 3;

	const ACL_PERMISSION_DENIED	= 100;

	const MISSING_HTTP_HEADER			= 11;
	const UNEXPECTED_HTTP_METHOD		= 12;
	const INVALID_PARAMETER				= 13;
	const MISSING_PARAMETER 			= 14;
	const UNKNOWN_METHOD 				= 15;
	const MALFORMED_REQUEST 			= 16;
	const AUTH_ERROR 					= 17;
	const TIMES_SKEW_ERROR 				= 18;
	const NOT_IMPLEMENTED_BY_EDITION	= 19;
	const INTERNAL_SERVER_ERROR 		= 20;
	const NO_SUCH_SERVER				= 22;
	const CANT_CONNECT_TO_SERVER		= 23;
	const INVALID_SERVER				= 24;
	const WRONG_PASSWORD				= 25;
	const SERVER_NOT_DISABLED			= 26;
	const RESTART_FAILED				= 27;
	const APPLICATION_DOES_NOT_EXISTS	= 28;
	const TEMPORARILY_LOCKED			= 29;
	const INVALID_SERVER_RESPONSE		= 30;
	const API_VERSION_NOT_SUPPORTED		= 31;
	const INSUFFICIENT_ACCESS_LEVEL		= 32;
	const CONFIGURATION_IMPORT_FAILED	= 33;
	const CONFIGURATION_SYSTEM_MISMATCH	= 34;
	const SERVER_ALREADY_CONNECTED		= 35;
	const NO_ACTIVE_SERVERS				= 36;
	const IMPORT_FAILED					= 37;
	const SERVER_NOT_LICENSED			= 38;
	const SERVER_NOT_CONFIGURED			= 39;
	const DIRECT_ACCESS_FORBIDDEN		= 40;
	const BASE_URL_CONFLICT				= 41;
	const NO_SUCH_APPLICATION			= 42;
	const APPLICATION_CONFLICT			= 43;
	const MISSING_VIRTUAL_HOST			= 44;
	const SERVER_VERSION_MISMATCH		= 45;
	const NO_ROLLBACK_AVAILABLE			= 46;
	const NO_SUCH_TRACE					= 47;
	const NO_SUCH_ISSUE					= 48;
	const NO_SUCH_EVENTGROUP			= 49;
	const NO_SUCH_EXTENSION				= 50;
	const NO_SUCH_MONITOR_RULE			= 51;
	const NO_SUCH_AUDIT_MESSAGE			= 52;
	const SMTP_HOST_IS_MISSING			= 53;
	const SMTP_PORT_IS_MISSING			= 54;
	const SMTP_CONNECTION_CLASS_IS_MISSING = 55;
	const EMAIL_SEND_TRANSPORT_IS_MISSING = 56;
	const LOG_FILE_NOT_READABLE 		= 56;
	const OUTPUT_TYPES_LIMITED 			= 57;
	const NO_SUCH_FILTER				= 58;
	const SERVER_NOT_READY				= 59;
	const WEBAPI_KEY_REMOVE_FAILED		= 60;
	const WEBAPI_KEY_ADD_FAILED			= 61;
	const WEBAPI_VALUE_ADD_FAILED		= 62;
	const WEBAPI_VALUE_REMOVE_FAILED	= 63;
	const WEBAPI_VALUE_UPDATE_FAILED	= 64;

	const PERMISSIONS = 100;

}
