<script type="text/javascript">
var url = baseUrl() + 'api/key';
$(document).ready(function() {
	$(".content").ajaxWithEffect(url, function(data) {
		populateKeys(data);
		$.modal.defaults.resizable = false;
		var content = $('div.modal_content').clone();
		$(content).find('form').attr('id', 'api_keys');
		$("a.com_btn").bind('click', function(e) {
			e.preventDefault();
			$.modal({
				content: content.html(),
				maxWidth: 500,
				buttons: {
					'CANCEL': function(win) {
						win.closeModal();
					},
					'+ ADD KEY': function(win) { 
						$(this).ajaxWithEffect(url, $("#api_keys").serializeArray(), function(data) {
							win.closeModal();
							populateKeys(data);
						});
					}
				}
			});
		});
	});	
});
</script>


	<div class="sub-navigation">
		<ul>
			<li><a href="/settings">GENERAL</a></li>
			<li><a href="/settings/keys" class="active">KEYS</a></li>
			<li><a href="/settings/hooks">HOOKS</a></li>
			<li><a href="/settings/subscriptions">SUBSCRIPTIONS</a></li>
		</ul>
	</div>

	<div class="clear"></div>

	<div class="line"></div>

	<div class="in author">
		<a class="txt_right com_btn" href="">+ ADD KEY</a>
		<h2>Create API Keys</h2>		
	</div>

	<div class="line"></div>


	<div class="in">	
		<table width="850" border="0" cellspacing="0" cellpadding="10" class="table_main" >
			<thead>
			  <tr style="background-color:#d9d8d8; font-size:14px;">
				<th id="name"><strong>NAME</strong></th>
				<th id="hash"><strong>HASH</strong></th>
				<th><strong>ACTIONS</strong></th>
			  </tr>
			</thead>
		</table>			
	</div>


	<div style="display: none;" class="modal_content">
		<div class="in author">
			<h2>Add New API Key</h2>
			<p></p>
		</div>
		<div class="in">
			<div class="line"></div>
			<div class="forms" style="">
				<form name="keys_form" method="post" action="">
					<?php 
						if (!$this->getAcl()->isAllowed($this->getIdentity()->getRole(), $this->resourceRoute, self::PERMISSION_CREATE_ALL)):
					?>
						<p><strong>USERNAME</strong>&nbsp;
						<input type="text" name="username"/></p>
					<?php
						endif;
					?>
					<p><strong>NAME</strong>&nbsp;
					<input type="text" name="name"/></p>
					<div class="line"></div>
				</form>
			</div>
		</div>
	</div>