
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="login-panel panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Please Sign In</h3>
            </div>
            <div class="panel-body">
                <div id="errorMessage"></div>
                <form id="login_form" role="form" method="post">
                    <fieldset>
                    	<?php if (!empty($data['params']) && !empty($data['params']['redirectUrl'])): ?>
                    		<input type="hidden" name="redirectUrl" value="<?php echo $data['params']['redirectUrl']; ?>">
                    	<?php endif ; ?>
                        <div class="form-group">
                            <input id="username" class="form-control" placeholder="E-mail" name="username" type="email" autofocus>
                        </div>
                        <div class="form-group">
                            <input id="password" class="form-control" placeholder="Password" name="password" type="password" value="">
                        </div>
                        <div class="checkbox">
                            <label>
                                <input name="remember" type="checkbox" value="Remember Me">Remember Me
                            </label>
                        </div>
                        <!-- Change this to a button or input when using this as a form -->
                        <input type="submit" name="login-btn" value="Login" class="btn btn-lg btn-success btn-block">
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>
