<?php $this->script(array(
    '/assets/js/plugins/dataTables/jquery.dataTables.js',
    '/assets/js/plugins/dataTables/dataTables.bootstrap.js',
    '/assets/js/plugins/retext/retext-codes.js'
)); ?>
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"><?php echo $this->getTitle(); ?> </h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div id="errorMessage"></div>
        	<p>
                <button class="btn btn-primary" data-toggle="modal" data-target="#codeFormModal">Add Code</button>
                <button id="btnDelete" class="btn btn-danger disabled">Delete</button>
            </p>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <?php echo $this->getTitle(); ?>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover" id="dataTables-codes">
                            <thead>
                                <tr>
                                    <th>Code</th>
                                    <th>Message</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                    <!-- /.table-responsive -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
</div>
<!-- /#page-wrapper -->
<div class="modal fade" id="codeFormModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Add Retext Code</h4>
            </div>

            <div class="modal-body">
                <div id="form-errorMessage"></div>
                <!-- The form is placed inside the body of modal -->
                <form id="codeForm" role="form" method="post" class="form-horizontal">
                    <div class="form-group">
                        <div class="col-sm-12">
                            <input type="text" class="form-control" id="retextCode" name="code" placeholder="TXT Code" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-12">
                            <textarea name="message" class="form-control" id="retextMessage" rows="3" placeholder="Short Message"></textarea>
                            <p class="help-block">Messages over 160 characters will be split up and sent as seperate texts.</p>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-12 ">
                            <button type="submit" class="btn btn-primary btn-block btn-lg">Add Code</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>\



   